### PR TITLE
Check that package is in registry

### PR DESCRIPTION
**Pull request by timholy**
This was necessary when I ran RetroCap on HolyLabRegistry.

### CODE REVIEW

**Review by DilumAluthge — APPROVED** [review]

**Comment by DilumAluthge** [comment]
Looks good to me! Merge whenever you're ready.

(I think this repo has Bors enabled, so to merge, just comment `bors merge`.)

**Comment by timholy** [comment]
bors merge

**Comment by timholy** [comment]
bors merge

**Comment by DilumAluthge** [comment]
bors merge

**Pull request merged**
